### ISSUE TITLE
Pop-up mode only shows "DeepL" logo

### ISSUE THREAD

**Issue by leo-liar** [sakusaku3939/DeepLAndroid#135]
Hello,
since few versions when trying to use the pop-up it only shows the "DeepL" logo (and some kind of flashing animation) and that's it – no translation is shown.

This is independent of the app from which I try to use the pop-up.

![Image](https://github.com/user-attachments/assets/62fe4421-1920-425a-b37b-1b1a2b251ac0)

(In the screenshot I tried to translate my issue text from above.)

**Comment by sakusaku3939** [comment]
This has been fixed in v9.0 🎉
https://github.com/sakusaku3939/DeepLAndroid/releases/tag/v9.0

**Comment by leo-liar** [comment]
Awesome! Can confirm the the Pop-up works again. Thank you very much for the quick fix!

**Comment by borg17a** [comment]
No, pop-up is still not working, at least not on my Pixel 5 with Android 14.

**Comment by sakusaku3939** [comment]
@borg17a 
I could not reproduce this on my Android 14 simulator...
Please reinstall [v9.0](https://github.com/sakusaku3939/DeepLAndroid/releases/tag/v9.0) after uninstalling and let me know the result, as the previous version may still be present.
Also, from the settings screen, please let me know if it works with pop-up mode off.
Thank you for your time.

**Comment by borg17a** [comment]
After uninstalling and reinstalling it worked. Thank you very much!
